(use test)

(load-relative "../ehk.util.coll.scm")
(load-relative "../ehk.lambda.parens.scm")
(load-relative "../ehk.lambda.reduce.scm")
(load-relative "../ehk.lambda.boolean.scm")
(load-relative "../ehk.lambda.run.scm")

(import ehk.util.coll)
(import ehk.lambda.parens)
(import ehk.lambda.reduce)
(import ehk.lambda.boolean)
(import ehk.lambda.run)

(test-begin)
(load-relative "ehk.util.coll.scm")
(load-relative "ehk.lambda.parens.scm")
(load-relative "ehk.lambda.reduce.scm")
(load-relative "ehk.lambda.boolean.scm")
(test-end)
